### ISSUE TITLE
[Feature Request] Command Line Ver/app switches

### ISSUE THREAD

**Issue by qfoxb** [jluims/RobloxDeathSoundReverter#1]
It'd be super nice to have a command line version for automation reasons, so i can have the program run on startup to replace oof with the old version automatically on startup 
Or, alternatively could you add command line switches so you could keep the same singular exe file?
Example
C:\Users\User\RobloxDeathSoundReverter.exe --oldoof
or
C:\Users\User\RobloxDeathSoundReverter.exe --newoof

Thanks!

**Comment by jluims** [comment]
I could attempt to implement it but does ROBLOX really change the sound back on startup?

**Comment by qfoxb** [comment]
No, but it reverts after the Roblox client updates so I'd like to automate it to replace it if it's been replaced on startup

**Comment by jluims** [comment]
Added [CLI program](https://github.com/jluims/RobloxDeathSoundReverter/releases/tag/1.0.0)
